Fix crash on attach when no process selected
DevToolsNET/meditation pull request #17
Opened 2023-10-13 14:11 UTC by acizmarik

This PR fixes an issue with propagating exception to user - causing a process crash. Instead we should show a message box and let user correct the mistake.

2023-10-16 19:31 UTC, aleksylum approved these changes

2023-12-11 13:56 UTC, LunarWhisper requested changes

2024-01-04 17:05 UTC, acizmarik commented on src/Meditation.UI/Controllers/AttachToProcessController.cs
>              if (processListViewModel.SelectedProcess is not { } selectedProcessInfo)
You are right. All relay commands now have exception handling. I will apply this behavior also for relay commands in other branches.

2024-02-06 13:03 UTC, LunarWhisper approved these changes

2024-02-08 10:12 UTC, merged